project:
  type: website
website:
  title: "Psychologie der Gesundheit"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd # Füge diese Zeile hinzu
        text: Forschung # Füge diese Zeile hinzu